spring:
  profiles:
    active: local
    include: infra

---
spring:
  config:
    activate:
      on-profile: local

springdoc:
  swagger-ui:
    urls:
      - name: "Kyonggiyo API"
        url: api.json
    path: swagger

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

web-application: true

logging:
  level:
    org:
      springframework:
        jdbc: debug

---
spring:
  config:
    activate:
      on-profile: dev