spring:
  profiles:
    active: default
    include: infra

web-application: true

springdoc:
  swagger-ui:
    urls:
      - name: "Kyonggiyo API"
        url: api.json
    path: swagger

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

logging:
  level:
    org:
      springframework:
        jdbc: debug
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev