spring:
  datasource:
    url: jdbc:h2:~/dev
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true