name: 경기요 CD

on:
  push:
    branches:
      - dev
      - main

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: 환경변수 파일 생성
        run: echo "${{ secrets.ENV_PROPERTIES }}" > .env
        working-directory: src/main/resources
      
      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gralde 캐싱
        id: gradle-cache
        uses: actions/cache@v3
        with: 
         path: |
           ~/.gradle/caches
           ~/.gradle/wrapper
         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         restore-keys: |
            ${{ runner.os }}-gradle-
            
      - if: steps.gradle-cache.outputs.cache-hit == 'true'
        run: echo 'gradle cache hit!'
      - if: steps.gradle-cache.outputs.cache-hit != 'true'
        run: echo 'gradle cache missed!'
        
      - name: Gradle 테스트 제외 빌드
        run: ./gradlew clean build -x test

      - name: Docker build & push to prod
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROD_REOP }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROD_REOP }}

      - name: Docker build & push to dev
        if: contains(github.ref, 'dev')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_REOP }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_REOP }}

      - name: 운영환경 배포
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROD_REOP }}
            sudo docker run -d -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_PROD_REOP }}
            sudo docker image prune -f

      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        if: contains(github.ref, 'dev')
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_PRIVATE_ACCESS_KEY }}
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_REOP }}
            sudo docker run -d -p 8082:8082 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_DEV_REOP }}
            sudo docker image prune -f
